Change from u7793aaa93ef05f

diff --git a/xwindow/bin/keyb b/xwindow/bin/keyb
--- a/xwindow/bin/keyb
+++ b/xwindow/bin/keyb
@@ -2,22 +2,23 @@
 # http://superuser.com/a/350336
 export DISPLAY="${DISPLAY:-:0.0}"
 export XAUTHORITY="${XAUTHORITY:-$HOME/.Xauthority}"
-(
-    sleep 1
+echo "$(date): keyb started" >> /tmp/keyb-debug.log
 
-    # https://bbs.archlinux.org/viewtopic.php?pid=1440918#p1440918
-    # Add this line to /etc/udev/rules.d/90-hojin-keyboard-mouse.rules
-    # ACTION=="add", ATTR{product}=="Microsoft USB Optical Mouse", RUN+="/home/hojin/.dotfiles/xwindow/bin/mouseleft"
-    # ACTION=="remove", ATTR{product}=="Microsoft USB Optical Mouse", RUN+="/home/hojin/.dotfiles/xwindow/bin/mousereset"
-    # ACTION=="add", ATTR{product}=="Apple Keyboard", RUN+="/home/hojin/.dotfiles/xwindow/bin/keyb"
-    # ACTION=="remove", ATTR{product}=="Apple Keyboard", RUN+="/home/hojin/.dotfiles/xwindow/bin/KEYBRESET"
+sleep 1
 
-    xset r rate 200 30
-    #numlockx
-    #setxkbmap -layout "de" -variant nodeadkeys
-    setxkbmap -layout us
-    xmodmap "${HOME}"/.Xmodmap
-    #(killall xbindkeys || true) &> /dev/null  # Continue even if exit status is 1
-    #xbindkeys  # Only one instance will run
-    notify-send -t 5000 "Keyboard settings applied"
-)&
+# https://bbs.archlinux.org/viewtopic.php?pid=1440918#p1440918
+# Add this line to /etc/udev/rules.d/90-hojin-keyboard-mouse.rules
+# ACTION=="add", ATTR{product}=="Microsoft USB Optical Mouse", RUN+="/home/hojin/.dotfiles/xwindow/bin/mouseleft"
+# ACTION=="remove", ATTR{product}=="Microsoft USB Optical Mouse", RUN+="/home/hojin/.dotfiles/xwindow/bin/mousereset"
+# ACTION=="add", ATTR{product}=="Apple Keyboard", RUN+="/home/hojin/.dotfiles/xwindow/bin/keyb"
+# ACTION=="remove", ATTR{product}=="Apple Keyboard", RUN+="/home/hojin/.dotfiles/xwindow/bin/KEYBRESET"
+
+xset r rate 200 30 >> /tmp/keyb-debug.log 2>&1
+#numlockx
+#setxkbmap -layout "de" -variant nodeadkeys
+setxkbmap -layout us >> /tmp/keyb-debug.log 2>&1
+xmodmap "${HOME}"/.Xmodmap >> /tmp/keyb-debug.log 2>&1
+#(killall xbindkeys || true) &> /dev/null  # Continue even if exit status is 1
+#xbindkeys  # Only one instance will run
+notify-send -t 5000 "Keyboard settings applied"
+echo "$(date): keyb completed" >> /tmp/keyb-debug.log
