feat: replace cron sync with systemd timers, add plocate indexing and jj snapshot support

diff --git a/script/sync_dotfiles b/script/sync_dotfiles
--- a/script/sync_dotfiles
+++ b/script/sync_dotfiles
@@ -2,7 +2,8 @@
 set -x
 GIT=${GIT_EXECUTABLE:-git}
 GIT_SUBREPO=${GIT_SUBREPO:-git-subrepo}
-HOSTNAME=${HOSTNAME:-hostname}
+MACHINE_NAME=$(hostnamectl --pretty 2>/dev/null | grep -v '\.')
+MACHINE_NAME=${MACHINE_NAME:-$(hostname -s)}
 cd "$1" || {
     echo "Error: No such directory as $1"; exit
 }
@@ -10,42 +11,37 @@ cd "$1" || {
 if jj root &>/dev/null 2>&1; then
     CHANGE_ID=$(jj log -r @ --no-graph -T 'change_id' 2>/dev/null)
     jj new
-    MSG=$("$1/bin/commit-msg" "$CHANGE_ID" 2>/dev/null) || MSG="Change from $($HOSTNAME -s)"
+    MSG=$("$1/bin/commit-msg" "$CHANGE_ID" 2>/dev/null) || MSG="Change from ${MACHINE_NAME}"
     jj describe "$CHANGE_ID" -m "$MSG"
 
     # Push bookmarks and @ to remote 'hj' with hostname prefix
     if jj git remote list 2>/dev/null | grep -q '^hj '; then
-        PREFIX=$($HOSTNAME -s)
-        for bm in $(jj bookmark list --all -T 'name ++ "\n"' 2>/dev/null); do
-            jj bookmark set "${PREFIX}/${bm}" -r "$bm" 2>/dev/null
-            jj git push --remote hj --bookmark "${PREFIX}/${bm}" --allow-new 2>/dev/null || true
-            jj bookmark delete "${PREFIX}/${bm}" 2>/dev/null
+        # Clean up any stale prefixed bookmarks
+        for bm in $(jj bookmark list --all -T 'name ++ "\n"' 2>/dev/null | grep "^${MACHINE_NAME}/"); do
+            jj bookmark delete "$bm" 2>/dev/null
         done
-        jj bookmark set "${PREFIX}/wc" -r @ 2>/dev/null
-        jj git push --remote hj --bookmark "${PREFIX}/wc" --allow-new 2>/dev/null || true
-        jj bookmark delete "${PREFIX}/wc" 2>/dev/null
+        # Push the just-described change first (before @ moves further)
+        jj bookmark set "${MACHINE_NAME}" -r "$CHANGE_ID" 2>/dev/null
+        jj git push --remote hj --bookmark "${MACHINE_NAME}" --allow-new 2>/dev/null || true
+        jj bookmark delete "${MACHINE_NAME}" 2>/dev/null
+        # Push all other bookmarks
+        for bm in $(jj bookmark list --all -T 'name ++ "\n"' 2>/dev/null | grep -v "^${MACHINE_NAME}/"); do
+            jj bookmark set "${MACHINE_NAME}/${bm}" -r "$bm" 2>/dev/null
+            jj git push --remote hj --bookmark "${MACHINE_NAME}/${bm}" --allow-new 2>/dev/null || true
+            jj bookmark delete "${MACHINE_NAME}/${bm}" 2>/dev/null
+        done
     fi
 else
     $GIT submodule foreach bash -c "$GIT add --verbose --all .
-        $GIT commit --verbose -m \"Change from $($HOSTNAME -s)\" && WILL_PUSH=yes
+        $GIT commit --verbose -m \"Change from ${MACHINE_NAME}\" && WILL_PUSH=yes
         $GIT pull --ff --verbose --no-edit --recurse-submodules=no
         test \$WILL_PUSH && $GIT push || true"
 
     $GIT add --verbose --all .
-    MSG=$("$1/bin/commit-msg" 2>/dev/null) || MSG="Change from $($HOSTNAME -s)"
+    MSG=$("$1/bin/commit-msg" 2>/dev/null) || MSG="Change from ${MACHINE_NAME}"
     $GIT commit --verbose --no-allow-empty -m "$MSG"
     $GIT pull --ff --verbose --no-edit
 
     $GIT_SUBREPO pull --verbose --all || $GIT_SUBREPO clean --verbose --all
     $GIT push --verbose
 fi
-
-#$GIT submodule foreach bash -c "$GIT add --verbose --all .
-    #$GIT commit --verbose -m \"Change from $($HOSTNAME -s)\" && WILL_PUSH=yes
-    #$GIT pull --ff --verbose --no-edit --recurse-submodules=no
-    #test \$WILL_PUSH && $GIT push || true"
-#$GIT add --verbose --all .
-#$GIT commit --verbose --no-allow-empty -m "Submodule update from $($HOSTNAME -s)"
-#$GIT pull --ff --verbose --no-edit --recurse-submodules=no
-
-#$GIT push --verbose
